on:
  push

name: Azure ARM CD Pipeline

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: run what-if
      uses: azure/arm-deploy@v1
      id: what-if
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: src/main.bicep
        parameters: 'storagePrefix=prefix storageSKU=Standard_LRS'
        additionalArguments: "--what-if"
        failOnStdErr: false

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build-and-validate
    environment: manual_approval

    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy ARM template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: src/main.bicep
        parameters: 'storagePrefix=prefix storageSKU=Standard_LRS'
        failOnStdErr: false
