on:
  push

name: Azure ARM CD Pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: run what-if
      uses: azure/arm-deploy@v1
      id: what-if
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: src/main.bicep
        parameters: 'storagePrefix=myprefix storageSKU=Standard_LRS'
        additionalArguments: "--what-if"

    - name: manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        minimum-approvals: 1
        issue-title: "Deploying ARM templates to Prod"
        issue-body: "Please review the what-if results and approve or deny the deployment:\n ${{ steps.what-if.outputs }}"

      # Deploy Bicep file
    - name: deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: src/main.bicep
        parameters: 'storagePrefix=myprefix storageSKU=Standard_LRS'
        failOnStdErr: false
