on:
  push:
  workflow_dispatch:

name: Azure ARM CD Pipeline

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run what-if
      uses: anthony-c-martin/bicep-action@validate-and-gen-markdown
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroup: ${{ secrets.AZURE_RG }}
        templateFile: src/main.bicep
        parametersFile: src/main.parameters.json
        whatIf: true

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build-and-validate
    environment: manual_approval
    concurrency: ${{ github.ref }}

    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy the ARM template to Prod
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: src/main.bicep
        parameters: 'storagePrefix=prefix storageSKU=Standard_LRS'
        failOnStdErr: false
