on:
  pull_request:
    types: [opened, reopened]

name: Azure ARM CI Pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Validate Bicep file
    - name: validate Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: src/main.bicep
        parameters: 'storagePrefix=myStorePrefix storageSKU=Standard_LRS'
        deploymentMode: Validate
        failOnStdErr: false
